apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ansible-job-template
  title: Ansible Job Template
  description: Define an Ansible Job Template within Ansible Automation Platform
  tags:
    - recommended
    - aap
spec:
  owner: janus-authors
  system: janus-idp
  type: service
  parameters:
    - title: Provide information about the GitHub location
      required:
        - githubOrg
        - repoName
        - owner
        - system
      properties:
        githubOrg:
          title: GitHub Organization
          type: string
        owner:
          title: Owner
          type: string
          description: Owner of the component
        repoName:
          title: Repository Name
          type: string
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
    - title: Ansible Job Definition
      required:
        - name
        - description
        - namespace
        - inventory
        - project
        - playbook
      properties:
        name:
          title: Name of the Ansible Job Template
          type: string
          description: A unique name for the Ansible Job Template
        playbook:
          title: Ansible Playbook
          type: string
          description: Specify an Ansible Playbook to run
        description:
          title: Description
          type: string
          description: Provide a description of the Job Template to be defined
        namespace:
          title: Namespace
          type: string
          description: Specify the namespace to launch the job
          default: aap
        inventory:
          title: Inventory
          type: string
          description: Specify the inventory to use for the job
          default: aap
        project:
          title: Project
          type: string
          description: Specify the Ansible Project to use for the job
          default: aap
        connection_secret:
          title: Connection Secret
          type: string
          description: Specify the connection secret to use for the job
          default: aapaccess
  steps:
    - id: template
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: argo/ansibleJobTemplates/
        values:
          component_id: ${{ parameters.name }}
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          inventory: ${{ parameters.inventory }}
          project: ${{ parameters.project }}
          playbook: ${{ parameters.playbook }}
          connection_secret: ${{ parameters.connection_secret }}

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/catalog-info-skeleton/
        values:
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          applicationType: api
          description: ${{ parameters.description }}

    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        title: ${{ parameters.name }}-job
        description: ${{ parameters.name }}-job
        repoUrl: github.com?owner=${{ parameters.githubOrg }}&repo=${{ parameters.repoName }}
        branchName: ${{ parameters.name }}-job

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}